In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath('..\\diffpy'))
import numpy as np
import matplotlib.pyplot as plt
from features import *
import pandas as pd
import trajectories as traj
import msds as msds
import numpy.ma as ma

In [2]:
xs, ys = traj.walks2D(steps=100, N=10, masked=True)
Ms, Gs = msds.trajsMSD(xs, ys)
dt = 0.1

n, _ = xs.shape
# Modified for arrays that have NaNs
mask = xs > -10000
cutoff = n*np.average(mask, axis=0)
n = cutoff.astype(np.int32) - 1

In [3]:
asyms(xs, ys)

(array([0.8238217 , 0.87849051, 0.35495404, 0.08587866, 0.95599479,
        0.97642373, 0.97594393, 0.80709978, 0.94141451, 0.57351671]),
 array([0.22002821, 0.17993394, 0.50329459, 0.73941184, 0.1060671 ,
        0.07723075, 0.07802218, 0.23135641, 0.12284864, 0.37162328]),
 array([0.22860382, 0.27643825, 0.05613213, 0.01128555, 0.39541657,
        0.45711494, 0.45527388, 0.21669997, 0.36402215, 0.11086437]),
 array([1.47322335, 1.31266915, 1.67576141, 2.02620076, 2.35507632,
        1.51562943, 2.95195789, 2.14423954, 2.87654109, 2.40008849]))

In [ ]:
efficiencies(xs, ys)

In [ ]:
netD = (xs[-1, :] - xs[0, :])**2 + (ys[-1, :] - ys[0, :])**2
total = np.sum(np.diff(xs, axis=0)**2 + np.diff(ys, axis=0)**2, axis=0)

In [ ]:
np.diag(xs[n, :])

In [ ]:
n, _ = Ms.shape
# Modified for arrays that have NaNs
mask = Ms > -10000
cutoff = n*np.average(mask, axis=0)
n = cutoff
Ds = (Ms[1, :] - Ms[0, :])/4
rs = np.sqrt(np.max(np.diff(xs, axis=0)**2 + np.diff(ys, axis=0)**2, axis=0))/2

In [ ]:
Ds

In [ ]:
n, N = Ms.shape
mask = Ms > -10000
cutoff = n*np.average(mask, axis=0)

#Ms[:int(cutoff[0]), 0]

In [ ]:
a1, a2, a3, Ks = asyms(xs, ys)

In [ ]:
Ds, alphas = anomModelN(Ms, dt)

In [ ]:
n = xs[:, 0].shape[0]
mask = xs[:, 0] > -10000
cutoff = n*np.average(mask)

In [ ]:
aspectRatios(xs, ys)

In [ ]:
cutoff

In [ ]:
n, N = xs.shape
Nxy, nxy = np.meshgrid(np.linspace(0, N-1, N), np.linspace(0, n-1, n))
cutoff = np.tile(np.random.randint(low=20, high=n, size=(1, N)), (n, 1))
mask = nxy > cutoff

In [ ]:
xs, ys = ma.array(xs, mask=mask), ma.array(ys, mask=mask)

In [ ]:
cutoff[0, 0:20]

In [ ]:
n-1 - n*np.average(mask, axis=0)

In [ ]:
type(xs) == type(ma.array([0], mask=['False']))

In [ ]:
xs.copy()

In [ ]:
x, y = xs.copy(), ys.copy()
steps, N = x.shape
mx1, mx2 = np.zeros((steps, steps, N)), np.zeros((steps, steps, N))
my1, my2 = np.zeros((steps, steps, N)), np.zeros((steps, steps, N))

for i in range(N):
    mx1[:, :, i], mx2[:, :, i] = np.meshgrid(x[:, i], x[:, i])
    my1[:, :, i], my2[:, :, i] = np.meshgrid(y[:, i], y[:, i])


# mmsd = (mx1 - mx2)**2 + (my1 - my2)**2
# mmsddiag = np.ones((steps-1, steps-1, N))*np.nan

# mgaus = (mx1 - mx2)**4 + (my1 - my2)**4
# mgausdiag = np.ones((steps-1, steps-1, N))*np.nan

# for i in range(1, steps):
#     mmsddiag[i-1, i-1:, :] = np.transpose(np.diagonal(mmsd, offset=i))
#     mgausdiag[i-1, i-1:, :] = np.transpose(np.diagonal(mgaus, offset=i))

# msds = np.nanmean(mmsddiag, axis=1)
# gauss = 2*np.nanmean(mgausdiag, axis=1)/(3*msds**2) - 1

In [ ]:
test1, test2 = np.meshgrid(xs, xs)

In [ ]:
x